version: '3.8'
services:   
  mongo_db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
  api:
    container_name: appAdoption
    build: .
    ports:
      - 8000:5000
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/api
      - TEST_MONGO_URL=mongodb://mongo_db:27017/test
      - PORT=5000
      - SECRET_KEY="1234"
    depends_on:
      - mongo_db